// AUTO GENERATED BY JNIGEN 0.14.2. DO NOT EDIT!

// Copyright 2024 Adrian Verban

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' show Object, String, bool, double, int;
import 'dart:core' as core$_;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `com.zebra.sdk.printer.discovery.DiscoveredPrinter`
class DiscoveredPrinter extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JObjType<DiscoveredPrinter> $type;

  @jni$_.internal
  DiscoveredPrinter.fromReference(
    jni$_.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
      r'com/zebra/sdk/printer/discovery/DiscoveredPrinter');

  /// The type which includes information such as the signature of this class.
  static const nullableType = $DiscoveredPrinter$NullableType();
  static const type = $DiscoveredPrinter$Type();
  static final _id_address = _class.instanceFieldId(
    r'address',
    r'Ljava/lang/String;',
  );

  /// from: `public final java.lang.String address`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? get address =>
      _id_address.get(this, const jni$_.JStringNullableType());

  static final _id_getConnection = _class.instanceMethodId(
    r'getConnection',
    r'()Lcom/zebra/sdk/comm/Connection;',
  );

  static final _getConnection = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public abstract com.zebra.sdk.comm.Connection getConnection()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getConnection() {
    return _getConnection(
            reference.pointer, _id_getConnection as jni$_.JMethodIDPtr)
        .object<jni$_.JObject?>(const jni$_.JObjectNullableType());
  }

  static final _id_toString$1 = _class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? toString$1() {
    return _toString$1(reference.pointer, _id_toString$1 as jni$_.JMethodIDPtr)
        .object<jni$_.JString?>(const jni$_.JStringNullableType());
  }

  static final _id_getDiscoveryDataMap = _class.instanceMethodId(
    r'getDiscoveryDataMap',
    r'()Ljava/util/Map;',
  );

  static final _getDiscoveryDataMap = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public java.util.Map<java.lang.String, java.lang.String> getDiscoveryDataMap()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JMap<jni$_.JString?, jni$_.JString?>? getDiscoveryDataMap() {
    return _getDiscoveryDataMap(
            reference.pointer, _id_getDiscoveryDataMap as jni$_.JMethodIDPtr)
        .object<jni$_.JMap<jni$_.JString?, jni$_.JString?>?>(
            const jni$_.JMapNullableType<jni$_.JString?, jni$_.JString?>(
                jni$_.JStringNullableType(), jni$_.JStringNullableType()));
  }

  static final _id_equals = _class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public boolean equals(java.lang.Object object)`
  bool equals(
    jni$_.JObject? object,
  ) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(reference.pointer, _id_equals as jni$_.JMethodIDPtr,
            _$object.pointer)
        .boolean;
  }

  static final _id_hashCode$1 = _class.instanceMethodId(
    r'hashCode',
    r'()I',
  );

  static final _hashCode$1 = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallIntMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public int hashCode()`
  int hashCode$1() {
    return _hashCode$1(reference.pointer, _id_hashCode$1 as jni$_.JMethodIDPtr)
        .integer;
  }
}

final class $DiscoveredPrinter$NullableType
    extends jni$_.JObjType<DiscoveredPrinter?> {
  @jni$_.internal
  const $DiscoveredPrinter$NullableType();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/zebra/sdk/printer/discovery/DiscoveredPrinter;';

  @jni$_.internal
  @core$_.override
  DiscoveredPrinter? fromReference(jni$_.JReference reference) =>
      reference.isNull
          ? null
          : DiscoveredPrinter.fromReference(
              reference,
            );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectNullableType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<DiscoveredPrinter?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DiscoveredPrinter$NullableType).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DiscoveredPrinter$NullableType) &&
        other is $DiscoveredPrinter$NullableType;
  }
}

final class $DiscoveredPrinter$Type extends jni$_.JObjType<DiscoveredPrinter> {
  @jni$_.internal
  const $DiscoveredPrinter$Type();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/zebra/sdk/printer/discovery/DiscoveredPrinter;';

  @jni$_.internal
  @core$_.override
  DiscoveredPrinter fromReference(jni$_.JReference reference) =>
      DiscoveredPrinter.fromReference(
        reference,
      );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectNullableType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<DiscoveredPrinter?> get nullableType =>
      const $DiscoveredPrinter$NullableType();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DiscoveredPrinter$Type).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DiscoveredPrinter$Type) &&
        other is $DiscoveredPrinter$Type;
  }
}
