// AUTO GENERATED BY JNIGEN 0.14.2. DO NOT EDIT!

// Copyright 2024 Adrian Verban

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' show Object, String, bool, double, int;
import 'dart:core' as core$_;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import 'DiscoveredPrinter.dart' as discoveredprinter$_;

/// from: `com.zebra.sdk.printer.discovery.DiscoveredPrinterBluetooth`
class DiscoveredPrinterBluetooth extends discoveredprinter$_.DiscoveredPrinter {
  @jni$_.internal
  @core$_.override
  final jni$_.JObjType<DiscoveredPrinterBluetooth> $type;

  @jni$_.internal
  DiscoveredPrinterBluetooth.fromReference(
    jni$_.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
      r'com/zebra/sdk/printer/discovery/DiscoveredPrinterBluetooth');

  /// The type which includes information such as the signature of this class.
  static const nullableType = $DiscoveredPrinterBluetooth$NullableType();
  static const type = $DiscoveredPrinterBluetooth$Type();
  static final _id_friendlyName = _class.instanceFieldId(
    r'friendlyName',
    r'Ljava/lang/String;',
  );

  /// from: `public final java.lang.String friendlyName`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? get friendlyName =>
      _id_friendlyName.get(this, const jni$_.JStringNullableType());

  static final _id_new$ = _class.constructorId(
    r'(Ljava/lang/String;Ljava/lang/String;)V',
  );

  static final _new$ = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_NewObject')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public void <init>(java.lang.String string, java.lang.String string1)`
  /// The returned object must be released after use, by calling the [release] method.
  factory DiscoveredPrinterBluetooth(
    jni$_.JString? string,
    jni$_.JString? string1,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    return DiscoveredPrinterBluetooth.fromReference(_new$(
            _class.reference.pointer,
            _id_new$ as jni$_.JMethodIDPtr,
            _$string.pointer,
            _$string1.pointer)
        .reference);
  }

  static final _id_getConnection = _class.instanceMethodId(
    r'getConnection',
    r'()Lcom/zebra/sdk/comm/Connection;',
  );

  static final _getConnection = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public com.zebra.sdk.comm.Connection getConnection()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getConnection() {
    return _getConnection(
            reference.pointer, _id_getConnection as jni$_.JMethodIDPtr)
        .object<jni$_.JObject?>(const jni$_.JObjectNullableType());
  }
}

final class $DiscoveredPrinterBluetooth$NullableType
    extends jni$_.JObjType<DiscoveredPrinterBluetooth?> {
  @jni$_.internal
  const $DiscoveredPrinterBluetooth$NullableType();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/zebra/sdk/printer/discovery/DiscoveredPrinterBluetooth;';

  @jni$_.internal
  @core$_.override
  DiscoveredPrinterBluetooth? fromReference(jni$_.JReference reference) =>
      reference.isNull
          ? null
          : DiscoveredPrinterBluetooth.fromReference(
              reference,
            );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType =>
      const discoveredprinter$_.$DiscoveredPrinter$NullableType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<DiscoveredPrinterBluetooth?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 2;

  @core$_.override
  int get hashCode => ($DiscoveredPrinterBluetooth$NullableType).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DiscoveredPrinterBluetooth$NullableType) &&
        other is $DiscoveredPrinterBluetooth$NullableType;
  }
}

final class $DiscoveredPrinterBluetooth$Type
    extends jni$_.JObjType<DiscoveredPrinterBluetooth> {
  @jni$_.internal
  const $DiscoveredPrinterBluetooth$Type();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/zebra/sdk/printer/discovery/DiscoveredPrinterBluetooth;';

  @jni$_.internal
  @core$_.override
  DiscoveredPrinterBluetooth fromReference(jni$_.JReference reference) =>
      DiscoveredPrinterBluetooth.fromReference(
        reference,
      );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType =>
      const discoveredprinter$_.$DiscoveredPrinter$NullableType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<DiscoveredPrinterBluetooth?> get nullableType =>
      const $DiscoveredPrinterBluetooth$NullableType();

  @jni$_.internal
  @core$_.override
  final superCount = 2;

  @core$_.override
  int get hashCode => ($DiscoveredPrinterBluetooth$Type).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DiscoveredPrinterBluetooth$Type) &&
        other is $DiscoveredPrinterBluetooth$Type;
  }
}
