// AUTO GENERATED BY JNIGEN 0.14.2. DO NOT EDIT!

// Copyright 2024 Adrian Verban

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' show Object, String, bool, double, int;
import 'dart:core' as core$_;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import '../../../com/zebra/sdk/printer/discovery/DiscoveredPrinterBluetooth.dart'
    as discoveredprinterbluetooth$_;

/// from: `co.fieldos.zebra_link_os.DiscoveryHandlerBluetooth`
class DiscoveryHandlerBluetooth extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JObjType<DiscoveryHandlerBluetooth> $type;

  @jni$_.internal
  DiscoveryHandlerBluetooth.fromReference(
    jni$_.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
      r'co/fieldos/zebra_link_os/DiscoveryHandlerBluetooth');

  /// The type which includes information such as the signature of this class.
  static const nullableType = $DiscoveryHandlerBluetooth$NullableType();
  static const type = $DiscoveryHandlerBluetooth$Type();
  static final _id_onFound = _class.instanceMethodId(
    r'onFound',
    r'(Lcom/zebra/sdk/printer/discovery/DiscoveredPrinterBluetooth;)V',
  );

  static final _onFound = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public abstract void onFound(com.zebra.sdk.printer.discovery.DiscoveredPrinterBluetooth discoveredPrinterBluetooth)`
  void onFound(
    discoveredprinterbluetooth$_.DiscoveredPrinterBluetooth
        discoveredPrinterBluetooth,
  ) {
    final _$discoveredPrinterBluetooth = discoveredPrinterBluetooth.reference;
    _onFound(reference.pointer, _id_onFound as jni$_.JMethodIDPtr,
            _$discoveredPrinterBluetooth.pointer)
        .check();
  }

  static final _id_onFinished = _class.instanceMethodId(
    r'onFinished',
    r'()V',
  );

  static final _onFinished = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public abstract void onFinished()`
  void onFinished() {
    _onFinished(reference.pointer, _id_onFinished as jni$_.JMethodIDPtr)
        .check();
  }

  static final _id_onError = _class.instanceMethodId(
    r'onError',
    r'(Ljava/lang/String;)V',
  );

  static final _onError = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public abstract void onError(java.lang.String string)`
  void onError(
    jni$_.JString string,
  ) {
    final _$string = string.reference;
    _onError(reference.pointer, _id_onError as jni$_.JMethodIDPtr,
            _$string.pointer)
        .check();
  }

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<int, $DiscoveryHandlerBluetooth> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(
        0,
        descriptor.address,
        args.address,
      ),
    );
  }

  static final jni$_.Pointer<
          jni$_.NativeFunction<
              jni$_.JObjectPtr Function(
                  jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)>>
      _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d ==
          r'onFound(Lcom/zebra/sdk/printer/discovery/DiscoveredPrinterBluetooth;)V') {
        _$impls[$p]!.onFound(
          $a![0]!.as(
              const discoveredprinterbluetooth$_
                  .$DiscoveredPrinterBluetooth$Type(),
              releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
      if ($d == r'onFinished()V') {
        _$impls[$p]!.onFinished();
        return jni$_.nullptr;
      }
      if ($d == r'onError(Ljava/lang/String;)V') {
        _$impls[$p]!.onError(
          $a![0]!.as(const jni$_.JStringType(), releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $DiscoveryHandlerBluetooth $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'co.fieldos.zebra_link_os.DiscoveryHandlerBluetooth',
      $p,
      _$invokePointer,
      [
        if ($impl.onFound$async)
          r'onFound(Lcom/zebra/sdk/printer/discovery/DiscoveredPrinterBluetooth;)V',
        if ($impl.onFinished$async) r'onFinished()V',
        if ($impl.onError$async) r'onError(Ljava/lang/String;)V',
      ],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory DiscoveryHandlerBluetooth.implement(
    $DiscoveryHandlerBluetooth $impl,
  ) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return DiscoveryHandlerBluetooth.fromReference(
      $i.implementReference(),
    );
  }
}

abstract base mixin class $DiscoveryHandlerBluetooth {
  factory $DiscoveryHandlerBluetooth({
    required void Function(
            discoveredprinterbluetooth$_.DiscoveredPrinterBluetooth
                discoveredPrinterBluetooth)
        onFound,
    bool onFound$async,
    required void Function() onFinished,
    bool onFinished$async,
    required void Function(jni$_.JString string) onError,
    bool onError$async,
  }) = _$DiscoveryHandlerBluetooth;

  void onFound(
      discoveredprinterbluetooth$_.DiscoveredPrinterBluetooth
          discoveredPrinterBluetooth);
  bool get onFound$async => false;
  void onFinished();
  bool get onFinished$async => false;
  void onError(jni$_.JString string);
  bool get onError$async => false;
}

final class _$DiscoveryHandlerBluetooth with $DiscoveryHandlerBluetooth {
  _$DiscoveryHandlerBluetooth({
    required void Function(
            discoveredprinterbluetooth$_.DiscoveredPrinterBluetooth
                discoveredPrinterBluetooth)
        onFound,
    this.onFound$async = false,
    required void Function() onFinished,
    this.onFinished$async = false,
    required void Function(jni$_.JString string) onError,
    this.onError$async = false,
  })  : _onFound = onFound,
        _onFinished = onFinished,
        _onError = onError;

  final void Function(
      discoveredprinterbluetooth$_.DiscoveredPrinterBluetooth
          discoveredPrinterBluetooth) _onFound;
  final bool onFound$async;
  final void Function() _onFinished;
  final bool onFinished$async;
  final void Function(jni$_.JString string) _onError;
  final bool onError$async;

  void onFound(
      discoveredprinterbluetooth$_.DiscoveredPrinterBluetooth
          discoveredPrinterBluetooth) {
    return _onFound(discoveredPrinterBluetooth);
  }

  void onFinished() {
    return _onFinished();
  }

  void onError(jni$_.JString string) {
    return _onError(string);
  }
}

final class $DiscoveryHandlerBluetooth$NullableType
    extends jni$_.JObjType<DiscoveryHandlerBluetooth?> {
  @jni$_.internal
  const $DiscoveryHandlerBluetooth$NullableType();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lco/fieldos/zebra_link_os/DiscoveryHandlerBluetooth;';

  @jni$_.internal
  @core$_.override
  DiscoveryHandlerBluetooth? fromReference(jni$_.JReference reference) =>
      reference.isNull
          ? null
          : DiscoveryHandlerBluetooth.fromReference(
              reference,
            );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<DiscoveryHandlerBluetooth?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DiscoveryHandlerBluetooth$NullableType).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DiscoveryHandlerBluetooth$NullableType) &&
        other is $DiscoveryHandlerBluetooth$NullableType;
  }
}

final class $DiscoveryHandlerBluetooth$Type
    extends jni$_.JObjType<DiscoveryHandlerBluetooth> {
  @jni$_.internal
  const $DiscoveryHandlerBluetooth$Type();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lco/fieldos/zebra_link_os/DiscoveryHandlerBluetooth;';

  @jni$_.internal
  @core$_.override
  DiscoveryHandlerBluetooth fromReference(jni$_.JReference reference) =>
      DiscoveryHandlerBluetooth.fromReference(
        reference,
      );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<DiscoveryHandlerBluetooth?> get nullableType =>
      const $DiscoveryHandlerBluetooth$NullableType();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DiscoveryHandlerBluetooth$Type).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DiscoveryHandlerBluetooth$Type) &&
        other is $DiscoveryHandlerBluetooth$Type;
  }
}
