// AUTO GENERATED BY JNIGEN 0.14.2. DO NOT EDIT!

// Copyright 2024 Adrian Verban

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' show Object, String, bool, double, int;
import 'dart:core' as core$_;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `co.fieldos.zebra_link_os.ResultCallbacksInterface`
class ResultCallbacksInterface extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JObjType<ResultCallbacksInterface> $type;

  @jni$_.internal
  ResultCallbacksInterface.fromReference(
    jni$_.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
      r'co/fieldos/zebra_link_os/ResultCallbacksInterface');

  /// The type which includes information such as the signature of this class.
  static const nullableType = $ResultCallbacksInterface$NullableType();
  static const type = $ResultCallbacksInterface$Type();
  static final _id_onSuccess = _class.instanceMethodId(
    r'onSuccess',
    r'(Ljava/lang/String;)V',
  );

  static final _onSuccess = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public abstract void onSuccess(java.lang.String string)`
  void onSuccess(
    jni$_.JString string,
  ) {
    final _$string = string.reference;
    _onSuccess(reference.pointer, _id_onSuccess as jni$_.JMethodIDPtr,
            _$string.pointer)
        .check();
  }

  static final _id_onError = _class.instanceMethodId(
    r'onError',
    r'(Ljava/lang/String;)V',
  );

  static final _onError = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public abstract void onError(java.lang.String string)`
  void onError(
    jni$_.JString string,
  ) {
    final _$string = string.reference;
    _onError(reference.pointer, _id_onError as jni$_.JMethodIDPtr,
            _$string.pointer)
        .check();
  }

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<int, $ResultCallbacksInterface> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(
        0,
        descriptor.address,
        args.address,
      ),
    );
  }

  static final jni$_.Pointer<
          jni$_.NativeFunction<
              jni$_.JObjectPtr Function(
                  jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)>>
      _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onSuccess(Ljava/lang/String;)V') {
        _$impls[$p]!.onSuccess(
          $a![0]!.as(const jni$_.JStringType(), releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
      if ($d == r'onError(Ljava/lang/String;)V') {
        _$impls[$p]!.onError(
          $a![0]!.as(const jni$_.JStringType(), releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $ResultCallbacksInterface $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'co.fieldos.zebra_link_os.ResultCallbacksInterface',
      $p,
      _$invokePointer,
      [
        if ($impl.onSuccess$async) r'onSuccess(Ljava/lang/String;)V',
        if ($impl.onError$async) r'onError(Ljava/lang/String;)V',
      ],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory ResultCallbacksInterface.implement(
    $ResultCallbacksInterface $impl,
  ) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return ResultCallbacksInterface.fromReference(
      $i.implementReference(),
    );
  }
}

abstract base mixin class $ResultCallbacksInterface {
  factory $ResultCallbacksInterface({
    required void Function(jni$_.JString string) onSuccess,
    bool onSuccess$async,
    required void Function(jni$_.JString string) onError,
    bool onError$async,
  }) = _$ResultCallbacksInterface;

  void onSuccess(jni$_.JString string);
  bool get onSuccess$async => false;
  void onError(jni$_.JString string);
  bool get onError$async => false;
}

final class _$ResultCallbacksInterface with $ResultCallbacksInterface {
  _$ResultCallbacksInterface({
    required void Function(jni$_.JString string) onSuccess,
    this.onSuccess$async = false,
    required void Function(jni$_.JString string) onError,
    this.onError$async = false,
  })  : _onSuccess = onSuccess,
        _onError = onError;

  final void Function(jni$_.JString string) _onSuccess;
  final bool onSuccess$async;
  final void Function(jni$_.JString string) _onError;
  final bool onError$async;

  void onSuccess(jni$_.JString string) {
    return _onSuccess(string);
  }

  void onError(jni$_.JString string) {
    return _onError(string);
  }
}

final class $ResultCallbacksInterface$NullableType
    extends jni$_.JObjType<ResultCallbacksInterface?> {
  @jni$_.internal
  const $ResultCallbacksInterface$NullableType();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lco/fieldos/zebra_link_os/ResultCallbacksInterface;';

  @jni$_.internal
  @core$_.override
  ResultCallbacksInterface? fromReference(jni$_.JReference reference) =>
      reference.isNull
          ? null
          : ResultCallbacksInterface.fromReference(
              reference,
            );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<ResultCallbacksInterface?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ResultCallbacksInterface$NullableType).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ResultCallbacksInterface$NullableType) &&
        other is $ResultCallbacksInterface$NullableType;
  }
}

final class $ResultCallbacksInterface$Type
    extends jni$_.JObjType<ResultCallbacksInterface> {
  @jni$_.internal
  const $ResultCallbacksInterface$Type();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lco/fieldos/zebra_link_os/ResultCallbacksInterface;';

  @jni$_.internal
  @core$_.override
  ResultCallbacksInterface fromReference(jni$_.JReference reference) =>
      ResultCallbacksInterface.fromReference(
        reference,
      );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<ResultCallbacksInterface?> get nullableType =>
      const $ResultCallbacksInterface$NullableType();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ResultCallbacksInterface$Type).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ResultCallbacksInterface$Type) &&
        other is $ResultCallbacksInterface$Type;
  }
}
