// AUTO GENERATED BY JNIGEN 0.14.2. DO NOT EDIT!

// Copyright 2024 Adrian Verban

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' show Object, String, bool, double, int;
import 'dart:core' as core$_;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import 'DiscoveryHandlerBluetooth.dart' as discoveryhandlerbluetooth$_;

import 'ResultCallbacksInterface.dart' as resultcallbacksinterface$_;

/// from: `co.fieldos.zebra_link_os.ZebraLinkOsPlugin$Companion`
class ZebraLinkOsPlugin$Companion extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JObjType<ZebraLinkOsPlugin$Companion> $type;

  @jni$_.internal
  ZebraLinkOsPlugin$Companion.fromReference(
    jni$_.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
      r'co/fieldos/zebra_link_os/ZebraLinkOsPlugin$Companion');

  /// The type which includes information such as the signature of this class.
  static const nullableType = $ZebraLinkOsPlugin$Companion$NullableType();
  static const type = $ZebraLinkOsPlugin$Companion$Type();
  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_NewObject')
      .asFunction<
          jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory ZebraLinkOsPlugin$Companion(
    jni$_.JObject? defaultConstructorMarker,
  ) {
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return ZebraLinkOsPlugin$Companion.fromReference(_new$(
            _class.reference.pointer,
            _id_new$ as jni$_.JMethodIDPtr,
            _$defaultConstructorMarker.pointer)
        .reference);
  }
}

final class $ZebraLinkOsPlugin$Companion$NullableType
    extends jni$_.JObjType<ZebraLinkOsPlugin$Companion?> {
  @jni$_.internal
  const $ZebraLinkOsPlugin$Companion$NullableType();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lco/fieldos/zebra_link_os/ZebraLinkOsPlugin$Companion;';

  @jni$_.internal
  @core$_.override
  ZebraLinkOsPlugin$Companion? fromReference(jni$_.JReference reference) =>
      reference.isNull
          ? null
          : ZebraLinkOsPlugin$Companion.fromReference(
              reference,
            );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<ZebraLinkOsPlugin$Companion?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ZebraLinkOsPlugin$Companion$NullableType).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ZebraLinkOsPlugin$Companion$NullableType) &&
        other is $ZebraLinkOsPlugin$Companion$NullableType;
  }
}

final class $ZebraLinkOsPlugin$Companion$Type
    extends jni$_.JObjType<ZebraLinkOsPlugin$Companion> {
  @jni$_.internal
  const $ZebraLinkOsPlugin$Companion$Type();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lco/fieldos/zebra_link_os/ZebraLinkOsPlugin$Companion;';

  @jni$_.internal
  @core$_.override
  ZebraLinkOsPlugin$Companion fromReference(jni$_.JReference reference) =>
      ZebraLinkOsPlugin$Companion.fromReference(
        reference,
      );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<ZebraLinkOsPlugin$Companion?> get nullableType =>
      const $ZebraLinkOsPlugin$Companion$NullableType();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ZebraLinkOsPlugin$Companion$Type).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ZebraLinkOsPlugin$Companion$Type) &&
        other is $ZebraLinkOsPlugin$Companion$Type;
  }
}

/// from: `co.fieldos.zebra_link_os.ZebraLinkOsPlugin`
class ZebraLinkOsPlugin extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JObjType<ZebraLinkOsPlugin> $type;

  @jni$_.internal
  ZebraLinkOsPlugin.fromReference(
    jni$_.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class =
      jni$_.JClass.forName(r'co/fieldos/zebra_link_os/ZebraLinkOsPlugin');

  /// The type which includes information such as the signature of this class.
  static const nullableType = $ZebraLinkOsPlugin$NullableType();
  static const type = $ZebraLinkOsPlugin$Type();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Lco/fieldos/zebra_link_os/ZebraLinkOsPlugin$Companion;',
  );

  /// from: `static public final co.fieldos.zebra_link_os.ZebraLinkOsPlugin$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static ZebraLinkOsPlugin$Companion get Companion =>
      _id_Companion.get(_class, const $ZebraLinkOsPlugin$Companion$Type());

  static final _id_new$ = _class.constructorId(
    r'(Landroid/content/Context;)V',
  );

  static final _new$ = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_NewObject')
      .asFunction<
          jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public void <init>(android.content.Context context)`
  /// The returned object must be released after use, by calling the [release] method.
  factory ZebraLinkOsPlugin(
    jni$_.JObject context,
  ) {
    final _$context = context.reference;
    return ZebraLinkOsPlugin.fromReference(_new$(_class.reference.pointer,
            _id_new$ as jni$_.JMethodIDPtr, _$context.pointer)
        .reference);
  }

  static final _id_connect = _class.instanceMethodId(
    r'connect',
    r'(Ljava/lang/String;Lco/fieldos/zebra_link_os/ResultCallbacksInterface;)V',
  );

  static final _connect = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void connect(java.lang.String string, co.fieldos.zebra_link_os.ResultCallbacksInterface resultCallbacksInterface)`
  void connect(
    jni$_.JString string,
    resultcallbacksinterface$_.ResultCallbacksInterface
        resultCallbacksInterface,
  ) {
    final _$string = string.reference;
    final _$resultCallbacksInterface = resultCallbacksInterface.reference;
    _connect(reference.pointer, _id_connect as jni$_.JMethodIDPtr,
            _$string.pointer, _$resultCallbacksInterface.pointer)
        .check();
  }

  static final _id_disconnect = _class.instanceMethodId(
    r'disconnect',
    r'(Lco/fieldos/zebra_link_os/ResultCallbacksInterface;)V',
  );

  static final _disconnect = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void disconnect(co.fieldos.zebra_link_os.ResultCallbacksInterface resultCallbacksInterface)`
  void disconnect(
    resultcallbacksinterface$_.ResultCallbacksInterface
        resultCallbacksInterface,
  ) {
    final _$resultCallbacksInterface = resultCallbacksInterface.reference;
    _disconnect(reference.pointer, _id_disconnect as jni$_.JMethodIDPtr,
            _$resultCallbacksInterface.pointer)
        .check();
  }

  static final _id_startDiscovery = _class.instanceMethodId(
    r'startDiscovery',
    r'(Lco/fieldos/zebra_link_os/DiscoveryHandlerBluetooth;)V',
  );

  static final _startDiscovery = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void startDiscovery(co.fieldos.zebra_link_os.DiscoveryHandlerBluetooth discoveryHandlerBluetooth)`
  void startDiscovery(
    discoveryhandlerbluetooth$_.DiscoveryHandlerBluetooth
        discoveryHandlerBluetooth,
  ) {
    final _$discoveryHandlerBluetooth = discoveryHandlerBluetooth.reference;
    _startDiscovery(reference.pointer, _id_startDiscovery as jni$_.JMethodIDPtr,
            _$discoveryHandlerBluetooth.pointer)
        .check();
  }

  static final _id_printImage = _class.instanceMethodId(
    r'printImage',
    r'(Ljava/lang/String;IIIIILco/fieldos/zebra_link_os/ResultCallbacksInterface;)V',
  );

  static final _printImage = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Int32,
                        jni$_.Int32,
                        jni$_.Int32,
                        jni$_.Int32,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
              int,
              int,
              int,
              int,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void printImage(java.lang.String string, int i, int i1, int i2, int i3, int i4, co.fieldos.zebra_link_os.ResultCallbacksInterface resultCallbacksInterface)`
  void printImage(
    jni$_.JString string,
    int i,
    int i1,
    int i2,
    int i3,
    int i4,
    resultcallbacksinterface$_.ResultCallbacksInterface
        resultCallbacksInterface,
  ) {
    final _$string = string.reference;
    final _$resultCallbacksInterface = resultCallbacksInterface.reference;
    _printImage(
            reference.pointer,
            _id_printImage as jni$_.JMethodIDPtr,
            _$string.pointer,
            i,
            i1,
            i2,
            i3,
            i4,
            _$resultCallbacksInterface.pointer)
        .check();
  }

  static final _id_storeImage = _class.instanceMethodId(
    r'storeImage',
    r'(Ljava/lang/String;Ljava/lang/String;IILco/fieldos/zebra_link_os/ResultCallbacksInterface;)V',
  );

  static final _storeImage = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Int32,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              int,
              int,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void storeImage(java.lang.String string, java.lang.String string1, int i, int i1, co.fieldos.zebra_link_os.ResultCallbacksInterface resultCallbacksInterface)`
  void storeImage(
    jni$_.JString string,
    jni$_.JString string1,
    int i,
    int i1,
    resultcallbacksinterface$_.ResultCallbacksInterface
        resultCallbacksInterface,
  ) {
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$resultCallbacksInterface = resultCallbacksInterface.reference;
    _storeImage(
            reference.pointer,
            _id_storeImage as jni$_.JMethodIDPtr,
            _$string.pointer,
            _$string1.pointer,
            i,
            i1,
            _$resultCallbacksInterface.pointer)
        .check();
  }

  static final _id_write = _class.instanceMethodId(
    r'write',
    r'(Ljava/lang/String;Lco/fieldos/zebra_link_os/ResultCallbacksInterface;)V',
  );

  static final _write = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void write(java.lang.String string, co.fieldos.zebra_link_os.ResultCallbacksInterface resultCallbacksInterface)`
  void write(
    jni$_.JString string,
    resultcallbacksinterface$_.ResultCallbacksInterface
        resultCallbacksInterface,
  ) {
    final _$string = string.reference;
    final _$resultCallbacksInterface = resultCallbacksInterface.reference;
    _write(reference.pointer, _id_write as jni$_.JMethodIDPtr, _$string.pointer,
            _$resultCallbacksInterface.pointer)
        .check();
  }
}

final class $ZebraLinkOsPlugin$NullableType
    extends jni$_.JObjType<ZebraLinkOsPlugin?> {
  @jni$_.internal
  const $ZebraLinkOsPlugin$NullableType();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lco/fieldos/zebra_link_os/ZebraLinkOsPlugin;';

  @jni$_.internal
  @core$_.override
  ZebraLinkOsPlugin? fromReference(jni$_.JReference reference) =>
      reference.isNull
          ? null
          : ZebraLinkOsPlugin.fromReference(
              reference,
            );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<ZebraLinkOsPlugin?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ZebraLinkOsPlugin$NullableType).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ZebraLinkOsPlugin$NullableType) &&
        other is $ZebraLinkOsPlugin$NullableType;
  }
}

final class $ZebraLinkOsPlugin$Type extends jni$_.JObjType<ZebraLinkOsPlugin> {
  @jni$_.internal
  const $ZebraLinkOsPlugin$Type();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lco/fieldos/zebra_link_os/ZebraLinkOsPlugin;';

  @jni$_.internal
  @core$_.override
  ZebraLinkOsPlugin fromReference(jni$_.JReference reference) =>
      ZebraLinkOsPlugin.fromReference(
        reference,
      );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<ZebraLinkOsPlugin?> get nullableType =>
      const $ZebraLinkOsPlugin$NullableType();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ZebraLinkOsPlugin$Type).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ZebraLinkOsPlugin$Type) &&
        other is $ZebraLinkOsPlugin$Type;
  }
}
